saturday november 10



#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port3,           backleft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           frontright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backright,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//where is the place where it says to move forward for _____ seconds
//never mind! I found it!! :D
{
	motor[frontleft]=50;		//Set the leftMotor (motor1) to half power (50)
	motor[frontright]=50;  //Set the rightMotor (motor6) to half power (50)
	motor[backleft]=50;
	motor[backright]=50;
	sleep(3000);           //Wait for 3 seconds before continuing on in the program. I got it to 3!!

	motor[frontleft]=0;
	motor[frontright]=0;
	motor[backleft]=0;
	motor[backright]=0;
	sleep(3000);        //this program makes it stop for 3 seconds


	motor[frontleft]=-50;
	motor[frontright]=-50;
	motor[backleft]=-50 ;
	motor[backright]=-50;
	sleep(3000);       		//this part makes it go backward for 3 seconds

	   
    motor[frontleft]=-50;   //this is a test just to see what happens
  motor[backleft]=-50;
  motor[frontright]=50;
  motor[backright]=50;
    sleep(1500);
    

}



}
